# Neural Network Basics

## Topics Covered:

1. Linear Layers
   
   - Understanding linear transformations
   - Implementation in PyTorch
   - Bias terms

2. Activation Functions
   - ReLU, Sigmoid, Tanh
   - When to use each
   - Implementation and visualization

3. Building Neural Network Modules
   - nn.Module class
   - Creating custom layers
   - Forward method implementation

4. Loss Functions
   - Common loss functions
   - When to use each
   - Implementation examples

5. Optimizers
   - SGD
   - Adam
   - Learning rate selection

6. Basic Training Loops
   - Forward pass
   - Loss computation
   - Backward pass
   - Parameter updates

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

## Linear Layers

A linear layer performs the operation:
y = Wx + b

Let us implement this in PyTorch

In [3]:
# create a linear layer
in_features = 3
out_features = 2

linear_layer = nn.Linear(in_features, out_features)

# print the layer parameters
print(linear_layer.weight)
print(linear_layer.bias)


Parameter containing:
tensor([[ 0.4177, -0.5497,  0.0240],
        [ 0.0882,  0.1632,  0.4168]], requires_grad=True)
Parameter containing:
tensor([0.5553, 0.2438], requires_grad=True)


In [5]:
# create an input tensor
x = torch.tensor([1.0, 2.0, 3.0])

In [6]:
y = linear_layer(x)

In [7]:
y.shape

torch.Size([2])

In [8]:
y

tensor([-0.0545,  1.9088], grad_fn=<ViewBackward0>)

In [14]:
# manual computation yielding the same results:
manual_y = x @ linear_layer.weight.T + linear_layer.bias
manual_y

tensor([-0.0545,  1.9088], grad_fn=<AddBackward0>)

## Training a Linear Layer

Now that we understand how a linear layer transforms input, let's see how it learns. We'll:
1. Create a simple regression problem
2. Use a linear layer to solve it
3. Train the layer using gradient descent

Our task: Learn the transformation y = 2x + 1
- This is a simple linear relationship
- The weight should learn to be close to 2
- The bias should learn to be close to 1

In [ ]:
# Create synthetic data
x = torch.linspace(-10, 10, 100).reshape(-1, 1)  # Input values
y_true = 2 * x + 1  # True relationship we want to learn

# Add noise to the data
y = y_true + torch.randn(x.shape) * 2

# Plot the data
plt.scatter(x, y, label='Noisy data')